server:
  port: ${PORT:8080}

spring:
  application:
    name: jpa
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orm_compare}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # TypeORM의 synchronize: true
    show-sql: true      # TypeORM의 logging: true
    properties:
      hibernate:
        format_sql: true
